//  This file is automatically generated. DO NOT EDIT, all your changes would be lost.
//  https://pub.dartlang.org/packages/iconfont_convert

import 'package:flutter/material.dart';

class TestIcons {
  static const String _family = 'iconfont';
  
  TestIcons._();
  
  static const IconData check_circle = IconData(0xe77d, fontFamily: _family); // check-circle
  static const IconData ci = IconData(0xe77e, fontFamily: _family); // CI
  static const IconData dollar = IconData(0xe77f, fontFamily: _family); // Dollar
  static const IconData compass = IconData(0xe780, fontFamily: _family); // compass
  static const IconData close_circle = IconData(0xe781, fontFamily: _family); // close-circle
  static const IconData frown = IconData(0xe782, fontFamily: _family); // frown
  static const IconData info_circle = IconData(0xe783, fontFamily: _family); // info-circle
  static const IconData left_circle = IconData(0xe784, fontFamily: _family); // left-circle
  static const IconData down_circle = IconData(0xe785, fontFamily: _family); // down-circle
  static const IconData euro = IconData(0xe786, fontFamily: _family); // EURO
  static const IconData copyright = IconData(0xe787, fontFamily: _family); // copyright
  static const IconData minus_circle = IconData(0xe788, fontFamily: _family); // minus-circle
  static const IconData meh = IconData(0xe789, fontFamily: _family); // meh
  static const IconData plus_circle = IconData(0xe78a, fontFamily: _family); // plus-circle
  static const IconData play_circle = IconData(0xe78b, fontFamily: _family); // play-circle
  static const IconData question_circle = IconData(0xe78c, fontFamily: _family); // question-circle
  static const IconData pound = IconData(0xe78d, fontFamily: _family); // Pound
  static const IconData right_circle = IconData(0xe78e, fontFamily: _family); // right-circle
  static const IconData smile = IconData(0xe78f, fontFamily: _family); // smile
  static const IconData trademark = IconData(0xe790, fontFamily: _family); // trademark
  static const IconData time_circle = IconData(0xe791, fontFamily: _family); // time-circle
  static const IconData timeout = IconData(0xe792, fontFamily: _family); // time out
  static const IconData earth = IconData(0xe793, fontFamily: _family); // earth
  static const IconData yuan = IconData(0xe794, fontFamily: _family); // YUAN
  static const IconData up_circle = IconData(0xe795, fontFamily: _family); // up-circle
  static const IconData warning_circle = IconData(0xe796, fontFamily: _family); // warning-circle
  static const IconData sync = IconData(0xe797, fontFamily: _family); // sync
  static const IconData transaction = IconData(0xe798, fontFamily: _family); // transaction
  static const IconData undo = IconData(0xe799, fontFamily: _family); // undo
  static const IconData redo = IconData(0xe79a, fontFamily: _family); // redo
  static const IconData reload = IconData(0xe79b, fontFamily: _family); // reload
  static const IconData reloadtime = IconData(0xe79c, fontFamily: _family); // reload time
  static const IconData message = IconData(0xe79d, fontFamily: _family); // message
  static const IconData dashboard = IconData(0xe79e, fontFamily: _family); // dashboard
  static const IconData issuesclose = IconData(0xe79f, fontFamily: _family); // issues close
  static const IconData poweroff = IconData(0xe7a0, fontFamily: _family); // poweroff
  static const IconData logout = IconData(0xe7a1, fontFamily: _family); // logout
  static const IconData piechart = IconData(0xe7a2, fontFamily: _family); // pie chart
  static const IconData setting = IconData(0xe7a3, fontFamily: _family); // setting
  static const IconData eye = IconData(0xe7a4, fontFamily: _family); // eye
  static const IconData location = IconData(0xe7a5, fontFamily: _family); // location
  static const IconData edit_square = IconData(0xe7a6, fontFamily: _family); // edit-square
  static const IconData export = IconData(0xe7a7, fontFamily: _family); // export
  static const IconData save = IconData(0xe7a8, fontFamily: _family); // save
  static const IconData import = IconData(0xe7a9, fontFamily: _family); // Import
  static const IconData appstore = IconData(0xe7aa, fontFamily: _family); // app store
  static const IconData close_square = IconData(0xe7ab, fontFamily: _family); // close-square
  static const IconData down_square = IconData(0xe7ac, fontFamily: _family); // down-square
  static const IconData layout = IconData(0xe7ad, fontFamily: _family); // layout
  static const IconData left_square = IconData(0xe7ae, fontFamily: _family); // left-square
  static const IconData play_square = IconData(0xe7af, fontFamily: _family); // play-square
  static const IconData control = IconData(0xe7b0, fontFamily: _family); // control
  static const IconData codelibrary = IconData(0xe7b1, fontFamily: _family); // code library
  static const IconData detail = IconData(0xe7b2, fontFamily: _family); // detail
  static const IconData minus_square = IconData(0xe7b3, fontFamily: _family); // minus-square
  static const IconData plus_square = IconData(0xe7b4, fontFamily: _family); // plus-square
  static const IconData right_square = IconData(0xe7b5, fontFamily: _family); // right-square
  static const IconData project = IconData(0xe7b6, fontFamily: _family); // project
  static const IconData wallet = IconData(0xe7b7, fontFamily: _family); // wallet
  static const IconData up_square = IconData(0xe7b8, fontFamily: _family); // up-square
  static const IconData calculator = IconData(0xe7b9, fontFamily: _family); // calculator
  static const IconData interation = IconData(0xe7ba, fontFamily: _family); // interation
  static const IconData check_square = IconData(0xe7bb, fontFamily: _family); // check-square
  static const IconData border = IconData(0xe7bc, fontFamily: _family); // border
  static const IconData border_outer = IconData(0xe7bd, fontFamily: _family); // border-outer
  static const IconData border_top = IconData(0xe7be, fontFamily: _family); // border-top
  static const IconData border_bottom = IconData(0xe7bf, fontFamily: _family); // border-bottom
  static const IconData border_left = IconData(0xe7c0, fontFamily: _family); // border-left
  static const IconData border_right = IconData(0xe7c1, fontFamily: _family); // border-right
  static const IconData border_inner = IconData(0xe7c2, fontFamily: _family); // border-inner
  static const IconData border_verticle = IconData(0xe7c3, fontFamily: _family); // border-verticle
  static const IconData border_horizontal = IconData(0xe7c4, fontFamily: _family); // border-horizontal
  static const IconData radius_bottomleft = IconData(0xe7c5, fontFamily: _family); // radius-bottomleft
  static const IconData radius_bottomright = IconData(0xe7c6, fontFamily: _family); // radius-bottomright
  static const IconData radius_upleft = IconData(0xe7c7, fontFamily: _family); // radius-upleft
  static const IconData radius_upright = IconData(0xe7c8, fontFamily: _family); // radius-upright
  static const IconData radius_setting = IconData(0xe7c9, fontFamily: _family); // radius-setting
  static const IconData adduser = IconData(0xe7ca, fontFamily: _family); // add user
  static const IconData deleteteam = IconData(0xe7cb, fontFamily: _family); // delete team
  static const IconData deleteuser = IconData(0xe7cc, fontFamily: _family); // delete user
  static const IconData addteam = IconData(0xe7cd, fontFamily: _family); // addteam
  static const IconData user = IconData(0xe7ce, fontFamily: _family); // user
  static const IconData team = IconData(0xe7cf, fontFamily: _family); // team
  static const IconData areachart = IconData(0xe7d0, fontFamily: _family); // area chart
  static const IconData linechart = IconData(0xe7d1, fontFamily: _family); // line chart
  static const IconData barchart = IconData(0xe7d2, fontFamily: _family); // bar chart
  static const IconData pointmap = IconData(0xe7d3, fontFamily: _family); // point map
  static const IconData container = IconData(0xe7d4, fontFamily: _family); // container
  static const IconData database = IconData(0xe7d5, fontFamily: _family); // database
  static const IconData sever = IconData(0xe7d6, fontFamily: _family); // sever
}

class _PreviewIcon {
  const _PreviewIcon(this.icon, this.name, this.propName);

  final IconData icon;
  final String name;
  final String propName;
}

class TestIconsPreview extends StatelessWidget {
  const TestIconsPreview({Key? key}) : super(key: key);

  static const iconList = <_PreviewIcon>[
    _PreviewIcon(TestIcons.check_circle, "check_circle", "check-circle"),
    _PreviewIcon(TestIcons.ci, "ci", "CI"),
    _PreviewIcon(TestIcons.dollar, "dollar", "Dollar"),
    _PreviewIcon(TestIcons.compass, "compass", "compass"),
    _PreviewIcon(TestIcons.close_circle, "close_circle", "close-circle"),
    _PreviewIcon(TestIcons.frown, "frown", "frown"),
    _PreviewIcon(TestIcons.info_circle, "info_circle", "info-circle"),
    _PreviewIcon(TestIcons.left_circle, "left_circle", "left-circle"),
    _PreviewIcon(TestIcons.down_circle, "down_circle", "down-circle"),
    _PreviewIcon(TestIcons.euro, "euro", "EURO"),
    _PreviewIcon(TestIcons.copyright, "copyright", "copyright"),
    _PreviewIcon(TestIcons.minus_circle, "minus_circle", "minus-circle"),
    _PreviewIcon(TestIcons.meh, "meh", "meh"),
    _PreviewIcon(TestIcons.plus_circle, "plus_circle", "plus-circle"),
    _PreviewIcon(TestIcons.play_circle, "play_circle", "play-circle"),
    _PreviewIcon(TestIcons.question_circle, "question_circle", "question-circle"),
    _PreviewIcon(TestIcons.pound, "pound", "Pound"),
    _PreviewIcon(TestIcons.right_circle, "right_circle", "right-circle"),
    _PreviewIcon(TestIcons.smile, "smile", "smile"),
    _PreviewIcon(TestIcons.trademark, "trademark", "trademark"),
    _PreviewIcon(TestIcons.time_circle, "time_circle", "time-circle"),
    _PreviewIcon(TestIcons.timeout, "timeout", "time out"),
    _PreviewIcon(TestIcons.earth, "earth", "earth"),
    _PreviewIcon(TestIcons.yuan, "yuan", "YUAN"),
    _PreviewIcon(TestIcons.up_circle, "up_circle", "up-circle"),
    _PreviewIcon(TestIcons.warning_circle, "warning_circle", "warning-circle"),
    _PreviewIcon(TestIcons.sync, "sync", "sync"),
    _PreviewIcon(TestIcons.transaction, "transaction", "transaction"),
    _PreviewIcon(TestIcons.undo, "undo", "undo"),
    _PreviewIcon(TestIcons.redo, "redo", "redo"),
    _PreviewIcon(TestIcons.reload, "reload", "reload"),
    _PreviewIcon(TestIcons.reloadtime, "reloadtime", "reload time"),
    _PreviewIcon(TestIcons.message, "message", "message"),
    _PreviewIcon(TestIcons.dashboard, "dashboard", "dashboard"),
    _PreviewIcon(TestIcons.issuesclose, "issuesclose", "issues close"),
    _PreviewIcon(TestIcons.poweroff, "poweroff", "poweroff"),
    _PreviewIcon(TestIcons.logout, "logout", "logout"),
    _PreviewIcon(TestIcons.piechart, "piechart", "pie chart"),
    _PreviewIcon(TestIcons.setting, "setting", "setting"),
    _PreviewIcon(TestIcons.eye, "eye", "eye"),
    _PreviewIcon(TestIcons.location, "location", "location"),
    _PreviewIcon(TestIcons.edit_square, "edit_square", "edit-square"),
    _PreviewIcon(TestIcons.export, "export", "export"),
    _PreviewIcon(TestIcons.save, "save", "save"),
    _PreviewIcon(TestIcons.import, "import", "Import"),
    _PreviewIcon(TestIcons.appstore, "appstore", "app store"),
    _PreviewIcon(TestIcons.close_square, "close_square", "close-square"),
    _PreviewIcon(TestIcons.down_square, "down_square", "down-square"),
    _PreviewIcon(TestIcons.layout, "layout", "layout"),
    _PreviewIcon(TestIcons.left_square, "left_square", "left-square"),
    _PreviewIcon(TestIcons.play_square, "play_square", "play-square"),
    _PreviewIcon(TestIcons.control, "control", "control"),
    _PreviewIcon(TestIcons.codelibrary, "codelibrary", "code library"),
    _PreviewIcon(TestIcons.detail, "detail", "detail"),
    _PreviewIcon(TestIcons.minus_square, "minus_square", "minus-square"),
    _PreviewIcon(TestIcons.plus_square, "plus_square", "plus-square"),
    _PreviewIcon(TestIcons.right_square, "right_square", "right-square"),
    _PreviewIcon(TestIcons.project, "project", "project"),
    _PreviewIcon(TestIcons.wallet, "wallet", "wallet"),
    _PreviewIcon(TestIcons.up_square, "up_square", "up-square"),
    _PreviewIcon(TestIcons.calculator, "calculator", "calculator"),
    _PreviewIcon(TestIcons.interation, "interation", "interation"),
    _PreviewIcon(TestIcons.check_square, "check_square", "check-square"),
    _PreviewIcon(TestIcons.border, "border", "border"),
    _PreviewIcon(TestIcons.border_outer, "border_outer", "border-outer"),
    _PreviewIcon(TestIcons.border_top, "border_top", "border-top"),
    _PreviewIcon(TestIcons.border_bottom, "border_bottom", "border-bottom"),
    _PreviewIcon(TestIcons.border_left, "border_left", "border-left"),
    _PreviewIcon(TestIcons.border_right, "border_right", "border-right"),
    _PreviewIcon(TestIcons.border_inner, "border_inner", "border-inner"),
    _PreviewIcon(TestIcons.border_verticle, "border_verticle", "border-verticle"),
    _PreviewIcon(TestIcons.border_horizontal, "border_horizontal", "border-horizontal"),
    _PreviewIcon(TestIcons.radius_bottomleft, "radius_bottomleft", "radius-bottomleft"),
    _PreviewIcon(TestIcons.radius_bottomright, "radius_bottomright", "radius-bottomright"),
    _PreviewIcon(TestIcons.radius_upleft, "radius_upleft", "radius-upleft"),
    _PreviewIcon(TestIcons.radius_upright, "radius_upright", "radius-upright"),
    _PreviewIcon(TestIcons.radius_setting, "radius_setting", "radius-setting"),
    _PreviewIcon(TestIcons.adduser, "adduser", "add user"),
    _PreviewIcon(TestIcons.deleteteam, "deleteteam", "delete team"),
    _PreviewIcon(TestIcons.deleteuser, "deleteuser", "delete user"),
    _PreviewIcon(TestIcons.addteam, "addteam", "addteam"),
    _PreviewIcon(TestIcons.user, "user", "user"),
    _PreviewIcon(TestIcons.team, "team", "team"),
    _PreviewIcon(TestIcons.areachart, "areachart", "area chart"),
    _PreviewIcon(TestIcons.linechart, "linechart", "line chart"),
    _PreviewIcon(TestIcons.barchart, "barchart", "bar chart"),
    _PreviewIcon(TestIcons.pointmap, "pointmap", "point map"),
    _PreviewIcon(TestIcons.container, "container", "container"),
    _PreviewIcon(TestIcons.database, "database", "database"),
    _PreviewIcon(TestIcons.sever, "sever", "sever"),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('TestIcons'),
      ),
      body: SingleChildScrollView(
        child: GridView.count(
          shrinkWrap: true,
          crossAxisCount: 4,
          children: iconList.map((e) {
            return InkWell(
              onTap: () {
                //
              },
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Container(
                    margin: const EdgeInsets.only(bottom: 8),
                    child: Icon(e.icon),
                  ),
                  Text(e.name, style: const TextStyle(fontSize: 12), overflow: TextOverflow.ellipsis, maxLines: 1),
                  Text(e.propName, style: const TextStyle(fontSize: 12), overflow: TextOverflow.ellipsis, maxLines: 1),
                ],
              ),
            );
          }).toList(),
        ),
      ),
    );
  }
}
